---
title: "EDA"
author: "lulu zhang"
date: "7/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(sas7bdat)
library(tidyr)
library(tidyverse)
library(SASxport)
library(dplyr)
require(haven)
library(car)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')
require(ggplot2)
require(sandwich)
require(msm)
```


```{r incidence.by.race, echo=FALSE,  message=FALSE}
seer = readxl::read_xlsx("./seer.xlsx", sheet = 2) %>% 
  mutate(
    race = as.factor(race),
    gender = as.factor(gender), 
    race = dplyr::recode(race, 
                  `1` = "Black",
                  `0`  = "White"),
    gender = dplyr::recode(gender, 
                    `0` = "Male",
                    `1` = "Female"),
    age_grp = as.factor(age_grp),
    age_grp = dplyr::recode(age_grp,
                            `0` = "25-29 year olds",
                            `1` = "30-34 year olds",
                            `2` = "35-39 year olds",
                            `3` = "40-44 year olds",
                            `4` = "45-49 year olds")
  )

black_inc = seer %>% 
  filter(race == "Black") %>% 
  ggplot( aes(x = period, y = rate))+
   geom_line(aes(color = gender)) +
  facet_wrap(~age_grp)+
   labs(
    title = "CRC inc rates from 1975-2014 among Blacks",
    x = "Periods (5-year groups)",
    y = "Inc Rate of CRC",
    caption = "by 5-year age groups (25-49)"
  )

white_inc = seer %>% 
  filter(race == "White") %>% 
  ggplot( aes(x = period, y = rate))+
   geom_line(aes(color = gender)) +
  facet_wrap(~age_grp)+
   labs(
 title = "CRC inc rates from 1975-2014 among Whites",
    x = "Periods (5-year groups)",
    y = "Inc Rate of CRC",
    caption = "by 5-year age groups (25-49)"
  )

black_inc
white_inc
```

```{r  echo=FALSE, include=FALSE,  message=FALSE}
mean_wgtsx = read.csv("./rf_wghts.csv")
mean_wgts = mean_wgtsx %>% 
  mutate(
    gender = as.factor(gender),
    race = as.factor(race),
    race = dplyr::recode(race, 
                  `1` = "Black",
                  `0`  = "White",
                  `2` = "Other"),
    gender = dplyr::recode(gender, 
                    `0` = "Male",
                    `1` = "Female"),
     age_grp = as.factor(age_grp),
    age_grp = dplyr::recode(age_grp,
                            `0` = "25-29 year olds",
                            `1` = "30-34 year olds",
                            `2` = "35-39 year olds",
                            `3` = "40-44 year olds",
                            `4` = "45-49 year olds"),
    activity_level..0_Mean = as.numeric(as.character(activity_level..0_Mean)),
    activity_level..1_Mean = as.numeric(as.character(activity_level..1_Mean)),
    activity_level..2_Mean = as.numeric(as.character(activity_level..2_Mean)),
    activity_level..3_Mean = as.numeric(as.character(activity_level..3_Mean)),
     alc_freq..5_Mean= as.numeric(as.character(alc_freq..5_Mean)),
    alc_freq..4_Mean= as.numeric(as.character(alc_freq..4_Mean)),
    alc_freq..3_Mean = as.numeric(as.character(alc_freq..3_Mean)),
    alc_freq..2_Mean = as.numeric(as.character(alc_freq..2_Mean)),
    alc_freq..1_Mean = as.numeric(as.character(alc_freq..1_Mean)),
     alc_freq..0_Mean = as.numeric(as.character(alc_freq..0_Mean)),
    meat_freq_pmo..0_Mean = as.numeric(as.character(meat_freq_pmo..0_Mean)),
    meat_freq_pmo..1_Mean = as.numeric(as.character(meat_freq_pmo..1_Mean)),
    meat_freq_pmo..2_Mean = as.numeric(as.character(meat_freq_pmo..2_Mean)),
    meat_freq_pmo..3_Mean = as.numeric(as.character(meat_freq_pmo..3_Mean)),
    protein..0_Mean = as.numeric(as.character(protein..0_Mean)),
    protein..1_Mean = as.numeric(as.character(protein..1_Mean)),
    protein..2_Mean = as.numeric(as.character(protein..2_Mean)),
    protein..3_Mean = as.numeric(as.character(protein..3_Mean)),
    protein..4_Mean = as.numeric(as.character(protein..4_Mean)),
    fruits_veggies_pmo..0_ = as.numeric(as.character(fruits_veggies_pmo..0_)),
    fruits_veggies_pmo..1_ = as.numeric(as.character(fruits_veggies_pmo..1_)),
    fruits_veggies_pmo..2_ = as.numeric(as.character(fruits_veggies_pmo..2_)),
    fruits_veggies_pmo..3_ = as.numeric(as.character(fruits_veggies_pmo..3_)),
    fruits_veggies_pmo..4_ = as.numeric(as.character(fruits_veggies_pmo..4_)),
    protein..0_Mean = as.numeric(as.character(protein..0_Mean)),
    protein..1_Mean = as.numeric(as.character(protein..1_Mean)),
    protein..2_Mean = as.numeric(as.character(protein..2_Mean)),
    protein..3_Mean = as.numeric(as.character(protein..3_Mean)),
    protein..4_Mean = as.numeric(as.character(protein..4_Mean)),
    sat_fatty_acid.0_Mean = as.numeric(as.character(sat_fatty_acid.0_Mean)),
    sat_fatty_acid.1_Mean = as.numeric(as.character(sat_fatty_acid.1_Mean)),
    sat_fatty_acid.2_Mean = as.numeric(as.character(sat_fatty_acid.2_Mean)),
    sat_fatty_acid.3_Mean = as.numeric(as.character(sat_fatty_acid.3_Mean)),
    sat_fatty_acid.4_Mean = as.numeric(as.character(sat_fatty_acid.4_Mean)),
    still_thyroid_d.0_Mean = as.numeric(as.character(still_thyroid_d.0_Mean)),
    still_thyroid_d.1_Mean = as.numeric(as.character(still_thyroid_d.1_Mean)),
    still_thyroid_d.2_Mean = as.numeric(as.character(still_thyroid_d.2_Mean)),
    age_grp = as.factor( age_grp)
  ) 

head(mean_wgts)
```


```{r activity.level, echo=FALSE,  message=FALSE}
mean_wgts_activity = mean_wgts %>% 
  select(period, age_grp, race, gender, activity_level..0_Mean, activity_level..1_Mean, activity_level..2_Mean,
         activity_level..3_Mean) %>% 
  drop_na()

act_level_0 = mean_wgts_activity%>% 
  ggplot( aes(x = period, y = activity_level..0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for little to no activity level by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



act_level_1 = mean_wgts_activity%>% 
  ggplot( aes(x = period, y = activity_level..1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for moderate activity level by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")


act_level_2 = mean_wgts_activity%>% 
  ggplot( aes(x = period, y = activity_level..2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for moderate activity level by race and gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")


act_level_3 = mean_wgts_activity%>% 
  ggplot( aes(x = period, y = activity_level..3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for high activity level by race and gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



act_level_0
act_level_1
act_level_2
act_level_3

```

```{r alcohol, echo=FALSE,  message=FALSE}

mean_wgts_alc = mean_wgts %>% 
  select(period, age_grp, race, gender, alc_freq..5_Mean,alc_freq..4_Mean,alc_freq..3_Mean,
         alc_freq..2_Mean,alc_freq..1_Mean,alc_freq..0_Mean) %>% drop_na()




alc_freq_4 = mean_wgts_alc%>% 
  ggplot( aes(x = period, y = alc_freq..4_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for alcohol frequency (4 = everyday) by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")


alc_freq_3 = mean_wgts_alc%>% 
  ggplot( aes(x = period, y = alc_freq..3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for alcohol frequency (3= 2-3x per week) by race and gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")


alc_freq_2 = mean_wgts_alc%>% 
  ggplot( aes(x = period, y = alc_freq..2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for alcohol frequency (2 = 1-4x per month) by race and gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")


alc_freq_1 = mean_wgts_alc%>% 
  ggplot( aes(x = period, y = alc_freq..1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for alcohol frequency (1 = 3-12x per yr) by race and gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

alc_freq_0 = mean_wgts_alc%>% 
  ggplot( aes(x = period, y = alc_freq..0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for alcohol frequency (0 = none/less than 2-3x per yr) by race and gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

alc_freq_0
alc_freq_1
alc_freq_2
alc_freq_3
alc_freq_4


#mean_wgts %>% filter(race == "Black", gender == "Female", age_grp == "45-49 year olds")

```


```{r avg.drinks., echo=FALSE,  message=FALSE}
mean_wgtsx = read.csv("./rf_wghts.csv")
mean_wgtsx = mean_wgtsx %>% 
  mutate(
    gender = as.factor(gender),
    race = as.factor(race),
    race = dplyr::recode(race, 
                  `1` = "Black",
                  `0`  = "White", 
                  `2` = "Other"),
    gender = dplyr::recode(gender, 
                    `0` = "Male",
                    `1` = "Female"),
     age_grp = as.factor(age_grp),
    age_grp = dplyr::recode(age_grp,
                            `0` = "25-29 year olds",
                            `1` = "30-34 year olds",
                            `2` = "35-39 year olds",
                            `3` = "40-44 year olds",
                            `4` = "45-49 year olds")
  ) %>% 
  drop_na() %>% 
  select(period, age_grp, gender, race, avg_drinks_pday_pstyr.1_Mean, avg_drinks_pday_pstyr.2_Mean, avg_drinks_pday_pstyr.3_Mean,
         avg_drinks_pday_pstyr.4_Mean, avg_drinks_pday_pstyr.NA_Mean)

avg_drnks_1 = mean_wgtsx%>% 
  ggplot( aes(x = period, y = avg_drinks_pday_pstyr.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for average drinks per day in the past year (1-2x) by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

avg_drnks_2 = mean_wgtsx%>% 
  ggplot( aes(x = period, y = avg_drinks_pday_pstyr.2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for average drinks per day in the past year (3-5x) by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

avg_drnks_3 = mean_wgtsx%>% 
  ggplot( aes(x = period, y = avg_drinks_pday_pstyr.3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for average drinks per day in the past year (6-9x) by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

avg_drnks_4 = mean_wgtsx%>% 
  ggplot( aes(x = period, y = avg_drinks_pday_pstyr.4_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for average drinks per day in the past year (10+) by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



avg_drnks_1
avg_drnks_2
avg_drnks_3
avg_drnks_4

```

## current smoker, no/yes

```{r current.smoker, echo=FALSE,  message=FALSE}
mean_wgts_smoker = mean_wgts %>% 
  select(period, age_grp, race, gender, current_smkr.0_Mean, current_smkr.1_Mean, current_smkr.2_Mean, 
         current_smkr.3_Mean, current_smkr.NA_Mean) %>% 
  drop_na()


current_smkr_0 = mean_wgts_smoker%>% 
  ggplot( aes(x = period, y = current_smkr.0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for current smoker (0 = no) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

current_smkr_1 = mean_wgts_smoker%>% 
  ggplot( aes(x = period, y = current_smkr.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for current smoker (1 = yes) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

current_smkr_2 = mean_wgts_smoker%>% 
  ggplot( aes(x = period, y = current_smkr.2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for current smoker (2 = blank but applicable) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

current_smkr_3 = mean_wgts_smoker%>% 
  ggplot( aes(x = period, y = current_smkr.3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for current smoker (3 = missing) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



current_smkr_0
current_smkr_1
current_smkr_2

```

## diabetes y/n

```{r diabetes, echo=FALSE,  message=FALSE}
mean_wgts_diabetes = mean_wgts %>% 
  select(period, age_grp, race, gender,diabetes..0_Mean,diabetes..1_Mean,diabetes..2_Mean ) %>% 
  drop_na()


diabetes_0 = mean_wgts_diabetes%>% 
  ggplot( aes(x = period, y = diabetes..0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for no diabetes by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

diabetes_1 = mean_wgts_diabetes%>% 
  ggplot( aes(x = period, y = diabetes..1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for diabetes = yes by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

diabetes_2 = mean_wgts_diabetes%>% 
  ggplot( aes(x = period, y = diabetes..2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for unknown diabetes status by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

diabetes_0
diabetes_1
diabetes_2
```
#ever had 5 or more drinks in a day

```{r ever.5.or.more.drinks.pday, echo=FALSE,  message=FALSE}
mean_wgts_ever = mean_wgts %>% 
  select(period, age_grp, race, gender, ever_5_or_more_drinks_a_day.0_Me, ever_5_or_more_drinks_a_day.1_Me, ever_5_or_more_drinks_a_day.2_Me,
         ever_5_or_more_drinks_a_day.3_Me, ever_5_or_more_drinks_a_day.NA_M) %>% 
  drop_na()

ever5_0 = mean_wgts_ever%>% 
  ggplot( aes(x = period, y = ever_5_or_more_drinks_a_day.0_Me) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for ever 5 for more drinks a day (0=no) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

ever5_1 = mean_wgts_ever%>% 
  ggplot( aes(x = period, y = ever_5_or_more_drinks_a_day.1_Me) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for ever 5 for more drinks a day (1=yes) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

ever5_2 = mean_wgts_ever%>% 
  ggplot( aes(x = period, y = ever_5_or_more_drinks_a_day.2_Me) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for ever 5 for more drinks a day (2=dont know) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

ever5_3 = mean_wgts_ever%>% 
  ggplot( aes(x = period, y = ever_5_or_more_drinks_a_day.3_Me) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for ever 5 for more drinks a day (3 = missing) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



ever5_0
ever5_1
ever5_2
ever5_3

```

## thyroid disease y/n

```{r thyroid.disease, echo=FALSE,  message=FALSE}

thyroid = mean_wgts %>% 
  select(period, age_grp, race, gender, thyroid_d..0_Mean, thyroid_d..1_Mean, thyroid_d..2_Mean) %>% 
  drop_na()

thyroid_0 = thyroid%>% 
  ggplot( aes(x = period, y = thyroid_d..0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for thyroid disease (0 = no) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

thyroid_1 = thyroid%>% 
  ggplot( aes(x = period, y = thyroid_d..1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for thyroid disease (1 = yes) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



thyroid_0
thyroid_1

```


```{r hepA, echo=FALSE,  message=FALSE}
hepA = mean_wgts%>% 
  select(period, age_grp, race, gender, hepA_vacc.0_Mean, hepA_vacc.1_Mean, hepA_vacc.2_Mean, hepA_vacc.3_Mean) %>% 
  drop_na()

hepA_0 = hepA%>% 
  ggplot( aes(x = period, y = hepA_vacc.0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for hepA vaccine (0 = no doses)  by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

hepA_1 = hepA%>% 
  ggplot( aes(x = period, y = hepA_vacc.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for hepA vaccine (1 = less than 2 doses) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

hepA_2 = hepA%>% 
  ggplot( aes(x = period, y = hepA_vacc.2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for hepA vaccine (2 = at least 2 doses)  by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

hepA_0
hepA_1
hepA_2


```

## hep B vaccine

```{r hepB, echo= FALSE, message=FALSE}
hepB = mean_wgts%>% 
  select(period, age_grp, race, gender, hepB_vacc.0_Mean, hepB_vacc.1_Mean, hepB_vacc.2_Mean, hepB_vacc.3_Mean) %>% 
  drop_na()

hepB_0 = hepB%>% 
  ggplot( aes(x = period, y = hepB_vacc.0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for hepB vaccine (0 = no doses)  by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

hepB_1 = hepB%>% 
  ggplot( aes(x = period, y = hepB_vacc.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for hepB vaccine (1 = less than 3 doses) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

hepB_2 = hepB%>% 
  ggplot( aes(x = period, y = hepB_vacc.2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for hepb vaccine (all 3 doses)  by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")



hepB_0
hepB_1
hepB_2



```


```{r home.smokers, echo=FALSE, message=FALSE}
home_smoke = mean_wgts%>% 
  select(period, age_grp, race, gender, home_smokers.0_Mean, home_smokers.1_Mean, home_smokers.2_Mean, home_smokers.3_Mean) %>% 
  drop_na()

head(home_smoke)

home_smokers_0 = home_smoke%>% 
  ggplot( aes(x = period, y =  home_smokers.0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for no home smokers by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

home_smokers_1 = home_smoke%>% 
  ggplot( aes(x = period, y =  home_smokers.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for home smokers = yes by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

home_smokers_0
home_smokers_1
```

## meat consumed per month 

```{r meat_pmo, echo=FALSE, message=FALSE}
meat = mean_wgts %>% 
  select(period, age_grp, race, gender, meat_freq_pmo..0_Mean, meat_freq_pmo..1_Mean,meat_freq_pmo..2_Mean,meat_freq_pmo..3_Mean, meat_freq_pmo..4_Mean, meat_freq_pmo..5_Mean) %>% 
  drop_na() 

meat_0 = meat%>% 
  ggplot( aes(x = period, y =  meat_freq_pmo..0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for meat consumed per month (0 = none) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

meat_1 = meat%>% 
  ggplot( aes(x = period, y =  meat_freq_pmo..1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for meat consumed per month (1 = less than 1x/week) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

meat_2 = meat%>% 
  ggplot( aes(x = period, y =  meat_freq_pmo..2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for meat consumed per month (2 = 1-6x a week) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

meat_3 = meat%>% 
  ggplot( aes(x = period, y =  meat_freq_pmo..3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for meat consumed per month (3 = 1-7x a day) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

meat_0 
meat_1
meat_2
meat_3
```
```{r fruits.veggies, echo=FALSE,  message=FALSE}
fruits_veg = mean_wgts %>% 
  select(period, age_grp, race, gender, fruits_veggies_pmo..0_, fruits_veggies_pmo..1_, fruits_veggies_pmo..2_, fruits_veggies_pmo..3_,fruits_veggies_pmo..4_) %>% 
  drop_na()

fruits_veg_0 = fruits_veg%>% 
  ggplot( aes(x = period, y =  fruits_veggies_pmo..0_) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for fruits & veggies consumed per month (0 = none) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

fruits_veg_1 = fruits_veg%>% 
  ggplot( aes(x = period, y =  fruits_veggies_pmo..1_) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for fruits & veggies consumed per month (1 = less than once a week) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

fruits_veg_2 = fruits_veg%>% 
  ggplot( aes(x = period, y =  fruits_veggies_pmo..2_) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for fruits & veggies consumed per month (2 = 1-6x a week) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

fruits_veg_3 = fruits_veg%>% 
  ggplot( aes(x = period, y =  fruits_veggies_pmo..3_) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for fruits & veggies consumed per month (3 = 1-22x per day) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

fruits_veg_0
fruits_veg_1
fruits_veg_2
fruits_veg_3
```

## protein consumed 

```{r}
protein = mean_wgts %>% 
  select(period, age_grp, race, gender, protein..0_Mean, protein..1_Mean, protein..2_Mean, protein..3_Mean, protein..4_Mean) %>% 
  drop_na()

protein_0 = protein%>% 
  ggplot( aes(x = period, y =  protein..0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of protein consumed (0 = none) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

protein_1 = protein%>% 
  ggplot( aes(x = period, y =  protein..1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of protein consumed (1 = 1-4600g) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

protein_2 = protein%>% 
  ggplot( aes(x = period, y =  protein..2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of protein consumed (2 = 4501-6600g) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

protein_3 = protein%>% 
  ggplot( aes(x = period, y =  protein..3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of protein consumed (3 = 6601-9200g) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

protein_4 = protein%>% 
  ggplot( aes(x = period, y =  protein..4_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of protein consumed (4 = 9201+) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

protein_0
protein_1
protein_2
protein_3
protein_4
```


```{r}
sat_fat = mean_wgts %>% 
  select(period, age_grp, race, gender, sat_fatty_acid.0_Mean, sat_fatty_acid.1_Mean, sat_fatty_acid.2_Mean, sat_fatty_acid.3_Mean,sat_fatty_acid.4_Mean ) %>% 
  drop_na()


sat_fat_0 = sat_fat%>% 
  ggplot( aes(x = period, y = sat_fatty_acid.0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of saturated fatty acid consumed (0 = 0) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

sat_fat_1 = sat_fat%>% 
  ggplot( aes(x = period, y = sat_fatty_acid.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of saturated fatty acid consumed (1 = 1-1500g) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

sat_fat_2= sat_fat%>% 
  ggplot( aes(x = period, y = sat_fatty_acid.2_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of saturated fatty acid consumed (2 = 1501-2400) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

sat_fat_3 = sat_fat%>% 
  ggplot( aes(x = period, y = sat_fatty_acid.3_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of saturated fatty acid consumed (3 =  2401-3600g) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")


sat_fat_4 = sat_fat%>% 
  ggplot( aes(x = period, y = sat_fatty_acid.4_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for grams of saturated fatty acid consumed (4 = 3601+) by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

sat_fat_0
sat_fat_1
sat_fat_2
sat_fat_3
sat_fat_4
```

# still thyroid disease

```{r still.thyroid.disease, echo=FALSE, message=FALSE}
still_thyroid = mean_wgts %>% 
  select(period, age_grp, race, gender, still_thyroid_d.0_Mean, still_thyroid_d.1_Mean ) %>% 
  drop_na()


still_thyroid_0 = still_thyroid%>% 
  ggplot( aes(x = period, y = still_thyroid_d.0_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for still thyroid disease = no by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

still_thyroid_1 = still_thyroid%>% 
  ggplot( aes(x = period, y = still_thyroid_d.1_Mean) )+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~race+gender)+
  labs(
 title = "weighted means for still thyroid disease = yes by race & gender",
    x = "Periods (5-year groups from 1975-2014)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")

still_thyroid_0 
still_thyroid_1
```


## continuous variables

```{r load.continuous.data, echo=FALSE,  message=FALSE, include=FALSE}
diet = read.csv("./cts_var_eda.csv") %>% 
  select(-X, -VAR1, -poly_unsat_fa_g)


diet = diet %>% 
 mutate(
    race = as.factor(race),
    gender = as.factor(gender), 
    race = dplyr::recode(race, 
                  `1` = "Black",
                  `0`  = "White", 
                  `2` = "Other"),
    gender = dplyr::recode(gender, 
                    `0` = "Male",
                    `1` = "Female"),
    AGE_GRP = as.factor(AGE_GRP),
    AGE_GRP = dplyr::recode(AGE_GRP,
                            `0` = "25-29 year olds",
                            `1` = "30-34 year olds",
                            `2` = "35-39 year olds",
                            `3` = "40-44 year olds",
                            `4` = "45-49 year olds")
  )

```



```{r, echo=FALSE,  message=FALSE, include=FALSE}
library(reshape2)
diet_chol = diet %>% 
  select(period, race, gender, AGE_GRP, cholesterol_mg) %>% 
  drop_na() %>% 
  filter(
    race == c("Black", "White")
  )

#diet[, lapply(.SD, mean), by = .(period)]
                

#aggregate(diet[,5], list(diet$period), mean) 
 

chol = ggplot(diet_chol, aes(x=period, y=cholesterol_mg, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_grid(~race+gender)
chol

```



```{r alc.pmo, echo=FALSE,  message=FALSE}
alc = diet %>% 
  mutate(period = as.factor(period)) %>% 
  select(period, race, gender, AGE_GRP, alc_pmo) %>% 
  drop_na() %>% 
  filter(race == c("Black", "White"))
                      

alc_p = ggplot(alc, aes(x=period, y=alc_pmo, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_grid(~race+gender)+
labs(
    title = "average alcohol per month intake from 1975-2014",
    x = "Periods (5-year groups)",
    y = "alcohol per month",
    caption = "by 5-year age groups (25-49)"
  )

alc_p
## trying to find a better way to show this-only data for periods 3-4
```



```{r num.ppl.smoke.in.home, echo=FALSE, message=FALSE}
smoke_in_home = diet%>% 
  mutate(
    period = as.factor(period)
  ) %>% 
  select(period, race, gender, AGE_GRP, num_ppl_smoke_inhome) %>% 
   
  drop_na() %>%
  filter(race == c("Black", "White"))

smoke_in_home = ggplot(smoke_in_home, aes(x=period, y=num_ppl_smoke_inhome, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average number of people that smoked in the home from 1975-2014",
    x = "Periods (5-year groups)",
    y = "number of people who smoke in a household",
    caption = "by 5-year age groups (25-49)"
  )
smoke_in_home
```



## average drinks consumed a week in the past year

```{r drinks.perweek.pastyear, echo=FALSE, message=FALSE}
drinks = diet %>% 
  select(period, AGE_GRP, race, gender, drinks_pw_pstyr) %>% 
  drop_na() %>% 
  mutate(period = as.factor(period)) %>% 
  filter(race == c("Black", "White"))

drink_p  = ggplot(drinks, aes(x=period, y=drinks_pw_pstyr, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_grid(~race+gender)+
labs(
    title = "average drinks consumed per week in the past year from 1975-2014",
    x = "Periods (5-year groups)",
    y = "average drinks consumed per week",
    caption = "by 5-year age groups (25-49)"
  )
drink_p
```




## updated continuous variables

```{r}
cont = read.csv("./merged2_eda.csv") %>% mutate(
    race = as.factor(race),
    gender = as.factor(gender), 
    race = dplyr::recode(race, 
                  `1` = "Black",
                  `0`  = "White", 
                  `2` = "Other"),
    gender = dplyr::recode(gender, 
                    `0` = "Male",
                    `1` = "Female"),
    AGE_GRP = as.factor(AGE_GRP),
    AGE_GRP = dplyr::recode(AGE_GRP,
                            `0` = "25-29 year olds",
                            `1` = "30-34 year olds",
                            `2` = "35-39 year olds",
                            `3` = "40-44 year olds",
                            `4` = "45-49 year olds"),
    protein_gm = as.numeric(protein_gm),
    sat_fatty_acid = as.numeric(sat_fatty_acid),
    fat_gm = as.numeric(fat_gm),
    fat = coalesce(fat_g, fat_gm),
    protein = coalesce(protein_g, protein_gm),
    saturated_fat = coalesce(saturated_fat_g, sat_fatty_acid),
    genderx = as.factor(genderx),
    racex = as.factor(racex),
    weight1 = as.numeric(weight1),
    strata1 = as.integer(strata1),
    psu1 = as.integer(psu1),
    genderz = coalesce(gender, genderx),
    racez = coalesce(race, racex),
    weight = coalesce(MEC10YR, weight1),
    strata = coalesce(sddsrvyr, strata1),
    cluster = coalesce(sdmvpsu, psu1)
  ) %>% 
select(-protein_g, -protein_gm, -saturated_fat_g, -sat_fatty_acid, -fat_g, -fat_gm, -race, -racex, -gender, -genderx,
       -MEC10YR, -weight1,-sddsrvyr, -strata1,-sdmvpsu, -psu1, -VAR1, -seqn, -corresp_bc,- a_p)

cont = cont %>% 
  rename(gender = genderz,
         race = racez)
cont
```

```{r protein, echo=FALSE, message=FALSE}
prot = cont%>% 
  select(period, AGE_GRP, race, gender, protein) %>% 
  mutate(period = as.factor(period)) %>% 
  drop_na() %>% 
  filter( race == c("Black", "White"))

protein_p = ggplot(prot, aes(x=period, y=protein, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average protein in grams consumed from 1975-2014",
    x = "Periods (5-year groups)",
    y = "grams of protein",
    caption = "by 5-year age groups (25-49)"
  )
protein_p
```

```{r drinks.per.day, echo=FALSE, message=FALSE}
drinks = cont %>% 
  select(period, AGE_GRP, race, gender, avg_drnks_per_day_pastyr) %>% 
  drop_na() %>% 
  mutate(period = as.factor(period)) %>% 
  filter(race == c("Black", "White"))

drink_p  = ggplot(drinks, aes(x=period, y=avg_drnks_per_day_pastyr,group = AGE_GRP,  color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average drinks consumed per day in the past year from 1975-2014",
    x = "Periods (5-year groups)",
    y = "drinks consumed per day in the past year",
    caption = "by 5-year age groups (25-49)"
  )
drink_p
```


```{r sugar , echo=FALSE, message=FALSE}
sugar = cont %>% 
  select(AGE_GRP, period, race, gender, sugar_gm) %>% 
  mutate(period = as.factor(period)) %>% 
  drop_na() %>% 
  filter(race == c("Black", "White"))

sugar_p = ggplot(sugar, aes(x=period, y=sugar_gm,group = AGE_GRP,  color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average sugar in grams consumed from 1975-2014",
    x = "Periods (5-year groups)",
    y = "sugar(g)",
    caption = "by 5-year age groups (25-49)"
  )

sugar_p
```

```{r fiber, echo=FALSE, message=FALSE}
fiber_gm = cont %>% 
  select(period, AGE_GRP, race, gender, fiber_gm) %>% 
  drop_na() %>%
  mutate(period = as.factor(period)) %>% 
  filter(race == c("Black", "White"))

fiber_p = ggplot(fiber_gm, aes(x=period, y=fiber_gm, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average fiber intake in grams from 1975-2014",
    x = "Periods (5-year groups)",
    y = "fiber(g)",
    caption = "by 5-year age groups (25-49)"
  )
fiber_p
```

```{r cholesterol, echo=FALSE, message=FALSE}
cholesterol = cont %>% 
  select(period, race, gender, AGE_GRP, cholesterol_mg) %>% 
  drop_na() %>% 
  filter(
    race == c("Black", "White")
  )

#diet[, lapply(.SD, mean), by = .(period)]
                
chol_p =  
  ggplot(cholesterol, aes(x=period, y=cholesterol_mg, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average cholesterol intake in mg from 1975-2014",
    x = "Periods (5-year groups)",
    y = "cholesterol (mg)",
    caption = "by 5-year age groups (25-49)"
  )
chol_p
```

```{r}
saturated_fat = cont%>% 
  mutate(
    period = as.factor(period)
  ) %>% 
  select(period, race, gender, AGE_GRP, saturated_fat) %>% 
  drop_na() %>%
  filter(race == c("Black", "White"))

saturated_fat_p = ggplot(saturated_fat, aes(x=period, y=saturated_fat, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average grams of saturated fat consumed from 1975-2014",
    x = "Periods (5-year groups)",
    y = "saturated fat (g)",
    caption = "by 5-year age groups (25-49)"
  )
saturated_fat_p
```

```{r}
fat_g = cont %>% 
  select(period, AGE_GRP, race, gender, fat) %>% 
  drop_na() %>% 
  mutate(period = as.factor(period)) %>% 
  filter(race == c("Black", "White"))
  
fat_p = ggplot(fat_g, aes(x=period, y=fat, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average grams of  fat consumed from 1975-2014",
    x = "Periods (5-year groups)",
    y = "fat (g)",
    caption = "by 5-year age groups (25-49)"
  )
fat_p
```

```{r mono.sat.fat, echo=FALSE, message=FALSE}
mono = cont%>% 
  select(period, AGE_GRP, race, gender, mono_sat_fa_g) %>% 
  drop_na() %>% 
  mutate(period = as.factor(period)) %>% 
  filter(race == c("Black", "White"))

mono_p = ggplot(mono, aes(x=period, y=mono_sat_fa_g, group = AGE_GRP, color = AGE_GRP)) + stat_summary(fun.y="mean", geom="line")+
 facet_wrap(~race+gender)+
labs(
    title = "average grams of  mono_sat_fa_g consumed from 1975-2014",
    x = "Periods (5-year groups)",
    y = "monosaturated fatty acid (g)",
    caption = "by 5-year age groups (25-49)"
  )

mono_p
```

