---
title: "thyroid"
author: "lulu zhang"
date: "9/4/2020"
output: html_document
---
 ##thyroid disease
 took a look and tried to isolate thyroid, but for `yes` response, still has a negative beta coefficient?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sas7bdat)
library(tidyr)
library(tidyverse)
library(SASxport)
library(dplyr)
require(haven)
library(car)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')
require(ggplot2)
library(janitor)
library(ggplot2)
require(sandwich)
require(msm)
library(forcats)
require(ggplot2)
require(gridExtra)
library(sjPlot)
```

```{r load.data, include=FALSE}
nhes1 = read.csv("./nhesI_per.csv") %>% 
  janitor::clean_names()
nhes2 = read.csv("./nhesII_per.csv")%>% 
  janitor::clean_names()
nhes3 = read.csv("./nhesIII_per.csv")%>% 
  janitor::clean_names()
nhanes1 = read.csv("./nhanes1_per.csv")%>% 
  janitor::clean_names() %>% 
  mutate(thyroid_disease = as.factor(thyroid_disease)) %>% 
  rename(ever_had_thyroid_d = thyroid_disease)
nhanes2 = read.csv("./nhanes2_per.csv")%>% 
  janitor::clean_names() %>% 
  mutate(race = dplyr::recode(race,
                              `0` = "White",
                              `1` = "Black",
                              `2` = "Other"),
         race = fct_explicit_na(race, na_level = "Other"),
         gender = dplyr::recode(gender, `0` = "Male",
                                `1` = "Female"),
         ever_had_thyroid_d = as.factor(ever_had_thyroid_d))
nhanes3 = read.csv("./nhanes3_per.csv") %>% 
  janitor::clean_names() %>% 
  mutate(ever_had_thyroid_d = as.factor(ever_had_thyroid_d))
newnhanes = read.csv("./new_per.csv")%>% 
  janitor::clean_names()%>% 
  mutate(ever_had_thyroid_d = as.factor(ever_had_thyroid_d))
nhis = read.csv("./nhis_per.csv")%>% 
  janitor::clean_names() %>% 
  mutate(race = as.factor(race),
         gender = as.factor(gender),
         race = dplyr::recode(race,
                              `0` = "White",
                              `1` = "Black",
                              `2` = "Other"),
        gender = dplyr::recode(gender, `0` = "Male",
                               `1` = "Female"),
        ever_had_thyroid_d = as.factor(ever_had_thyroid_d))

seer = read.csv("./groupedseer.csv") %>% 
  janitor::clean_names()
```

```{r, include=FALSE}
n1thy = nhanes1 %>% 
  select(all_sampweight_1_65, age_grp, period, gender,race, ever_had_thyroid_d, period, psu, strata ) %>% 
  rename(weight = all_sampweight_1_65)
n2thy = nhanes2%>% 
  select(weight, age_grp, period, gender, race,ever_had_thyroid_d, period,psu, strata )
n3thy = nhanes3%>% 
  select(weight, age_grp, period, gender,race, ever_had_thyroid_d, period,psu, strata )
newthy = newnhanes%>% 
  select(weight, age_grp, period, gender,race, ever_had_thyroid_d, period,psu, strata )
nhisthy = nhis%>% 
  select(weight, age_grp, period, gender, race,ever_had_thyroid_d, period,psu, strata )

thy = rbind(n1thy, n2thy, n3thy, newthy, nhisthy) %>% 
  filter(gender %in% c("Male", "Female"),
         race %in% c("White", "Black", "Other"),
         age_grp %in% c(0:10),
         ever_had_thyroid_d %in% c("0", "1"))

```

```{r thy.plot, echo=FALSE, message=FALSE}
thyroid_means = read_xlsx("./bmi_means.xlsx", sheet = 37) %>% filter(age_grp %in% c(0:9)) %>% 
  mutate(race = as.factor(race),
         gender = as.factor(gender),
         age_grp = as.factor(age_grp),
         age_grp = dplyr::recode(age_grp,
                                 `0` = "0-4",
                                  `1` = "5-9",
                                  `2` = "10-14",
                                  `3` = "15-19",
                                  `4` = "20-24",
                                  `5` = "25-29",
                                  `6` = "30-34",
                                  `7` = "35-39",
                                  `8` = "40-44",
                                  `9` = "45-49"))

thyroid_means %>% filter(VarLevel == "1") %>% 
  ggplot( aes(x = period, y = Mean))+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~gender+race,  scales = "free_y")+
  labs(
 title = "weighted means of ever had thyroid disease = yes
 among 0-49 year olds by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")+  scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9,10,11),
  labels=c(`0` = "1960-1964",`1` = "1965-1969",
           `2` = "1970-1974",`3` = "1975-1979",`4` = "1980-1984", `5` = "1985-1989", `6`= "1990-1994",
           `7` = "1995-1999", `8` = "2000-2004", `9` = "2005-2009", `10` = "2010-2014", `11` = "2015-2018"))+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

thyroid_means %>% filter(VarLevel == "0") %>% 
  ggplot( aes(x = period, y = Mean))+
   geom_line(aes(color = age_grp )) + 
  facet_wrap(~gender+race,  scales = "free_y")+
  labs(
 title = "weighted means of ever had thyroid disease = no
 among 0-49 year olds by race & gender",
    x = "Periods (5-year groups)",
    y = "weighted mean",
    caption = "by 5-year age groups (25-49)")+  scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9,10,11),
  labels=c(`0` = "1960-1964",`1` = "1965-1969",
           `2` = "1970-1974",`3` = "1975-1979",`4` = "1980-1984", `5` = "1985-1989", `6`= "1990-1994",
           `7` = "1995-1999", `8` = "2000-2004", `9` = "2005-2009", `10` = "2010-2014", `11` = "2015-2018"))+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
```{r filter.gender, echo=FALSE, include=FALSE}
thymeans1= thyroid_means %>% 
  filter(VarLevel == 1)%>% 
   dplyr::rename(thymean1 = Mean,
         thy1 = VarLevel)%>% 
  mutate(age_grp = dplyr::recode(age_grp,
                                 `0-4` = "1",
                                 `5-9` = "2",
                                 `10-14` = "3",
                                 `15-19` = "4",
                                 `20-24` = "5",
                                 `25-29` = "6",
                                 `30-34` = "7",
                                 `35-39` = "8",
                                 `40-44` = "9",
                                 `45-49` = "10"),
         age_grp = as.numeric(age_grp),
         period = as.factor(period))

thyseer = merge(seer,thymeans1, by = c("period", "age_grp", "race", "gender"), all = TRUE) %>% 
  mutate(period = as.factor(period))
thyseer$period <- relevel(thyseer$period, ref = "9")
thyfem = thyseer %>% filter(gender == "Female")
thymale = thyseer %>% filter(gender == "Male")
```



```{r, echo=FALSE, message=FALSE}
fit<- glm(tot_count ~ age_grp + period, data=thyseer, family=poisson(), offset = lnpop)
thy<- glm(tot_count ~ age_grp + period+thymean1, data=thyseer, family=poisson(), offset = lnpop)

summary(fit)
summary(thy)

plot_model(thy)

#####female
fitf<- glm(tot_count ~ age_grp + period, data=thyfem, family=poisson(), offset = lnpop)
thyf<- glm(tot_count ~ age_grp + period+thymean1, data=thyfem, family=poisson(), offset = lnpop)

summary(fitf)
summary(thyf)

plot_model(thyf)

##male
fitm<- glm(tot_count ~ age_grp + period, data=thymale, family=poisson(), offset = lnpop)
thym<- glm(tot_count ~ age_grp + period+thymean1, data=thymale, family=poisson(), offset = lnpop)

summary(fitm)
summary(thym)

plot_model(thym)
```


try by race and gender 
```{r, include=FALSE}
wm =thyseer %>% filter(race == "White",
                   gender == "Male")

bm =thyseer %>% filter(race == "Black",
                   gender == "Male")

om =thyseer %>% filter(race == "Other",
                   gender == "Male")

wf =thyseer %>% filter(race == "White",
                   gender == "Female")

bf =thyseer %>% filter(race == "Black",
                   gender == "Female")

of =thyseer %>% filter(race == "Other",
                   gender == "Female")
```

```{r glm, echo=FALSE}
###########white 
#####female
fitfw<- glm(tot_count ~ age_grp + period, data=wf, family=poisson(), offset = lnpop)
thyfw<- glm(tot_count ~ age_grp + period+thymean1, data=wf, family=poisson(), offset = lnpop)

summary(fitfw)
summary(thyfw)

plot_model(thyfw)

##male
fitmw<- glm(tot_count ~ age_grp + period, data=wm, family=poisson(), offset = lnpop)
thymw<- glm(tot_count ~ age_grp + period+thymean1, data=wm, family=poisson(), offset = lnpop)

summary(fitmw)
summary(thymw)

plot_model(thymw)

#############black
#####female
fitfb<- glm(tot_count ~ age_grp + period, data=bf, family=poisson(), offset = lnpop)
thyfb<- glm(tot_count ~ age_grp + period+thymean1, data=bf, family=poisson(), offset = lnpop)

summary(fitfb)
summary(thyfb)

plot_model(thyfb)

##male
fitmb<- glm(tot_count ~ age_grp + period, data=bm, family=poisson(), offset = lnpop)
thymb<- glm(tot_count ~ age_grp + period+thymean1, data=bm, family=poisson(), offset = lnpop)

summary(fitmb)
summary(thymb)

plot_model(thymb)

############### other
#####female
fitfo<- glm(tot_count ~ age_grp + period, data=of, family=poisson(), offset = lnpop)
thyfo<- glm(tot_count ~ age_grp + period+thymean1, data=of, family=poisson(), offset = lnpop)

summary(fitfo)
summary(thyfo)

plot_model(thyfo)

##male
fitmo<- glm(tot_count ~ age_grp + period, data=om, family=poisson(), offset = lnpop)
thymo<- glm(tot_count ~ age_grp + period+thymean1, data=om, family=poisson(), offset = lnpop)

summary(fitmo)
summary(thymo)

plot_model(thymo)
```

